name: Preview

on:
  push:
    branches-ignore:
      - main

concurrency: preview-${{ github.workflow }}-${{ github.ref }}

jobs:
  preview:
    name: Preview
    if: github.repository_owner == 'isaac-mason'
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=4096'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: yarn

      - name: Build Packages
        run: ./ci/build-packages.sh
        shell: bash

      - name: Test
        run: yarn test

      # navmesh website
      - name: NavMesh Website - Pull Vercel Environment Information
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_NAVMESH_WEBSITE_PROJECT_ID }}

      - name: NavMesh Website - Build Project Artifacts
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_NAVMESH_WEBSITE_PROJECT_ID }}

      - name: NavMesh Website - Deploy Project Artifacts to Vercel
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_NAVMESH_WEBSITE_PROJECT_ID }}

      # storybook
      - name: Storybook - Pull Vercel Environment Information
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}

      - name: Storybook - Build Project Artifacts
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}

      - name: Storybook - Deploy Project Artifacts to Vercel
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}

      # docs
      - name: Docs - Pull Vercel Environment Information
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}

      - name: Docs - Build Project Artifacts
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}

      - name: Docs - Deploy Project Artifacts to Vercel
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn run vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
